name: goodtunes
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.7
  - conda-forge::numpy=1.18.1
  - conda-forge::pandas=1.0.2
  - conda-forge::pylint=2.4.4
  - conda-forge::jupyter=1.0.0
  - conda-forge::ipykernel=5.1.1
  - conda-forge::psycopg2=2.8.4
  - pip
  - pip:
      - black==19.10b0
      - pytest==5.3.5
      - pytest-cov==2.8.1
      - pytest-xdist==1.31.0
      - pytest-datafiles==2.0
